name: webf_video_player
description: WebF video player plugin.
version: 1.0.0
homepage: https://openwebf.com
repository: https://github.com/openwebf/plugins

environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: ">=3.0.2 <=3.0.5"

dependencies:
  flutter:
    sdk: flutter
  meta: "^1.3.0"
  webf: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.webfvideoplayer
        pluginClass: WebFVideoPlayerPlugin
      ios:
        pluginClass: FLTWebFVideoPlayerPlugin
