# This is a basic workflow that is manually triggered

name: Release plugins

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - main
  workflow_dispatch:  

env:
  flutterVersion: "2.2.0"
  packages: "[\"kraken_animation_player\", \"kraken_camera\", \"kraken_video_player\", \"kraken_websocket\", \"kraken_webview\"]"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
    steps:
      - id: matrix
        run: |
          echo '::set-output name=value::${{ env.packages }}'

  # This workflow contains a single job called "greet"
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [ setup ]
    strategy:
      fail-fast: false
      matrix:
        value: ${{fromJson(needs.setup.outputs.matrix)}}
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.flutterVersion }}
    - name: Publish
      uses: k-paxian/dart-package-publisher@master
      with:
        credentialJson: ${{ secrets.CREDENTIAL_JSON }}
        force: true
        flutter: true
        skipTests: true
        relativePath: ./packages/${{ matrix.value }}